version: "3.9"
services:
  db:
    image: postgres
    hostname: 0.0.0.0
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sharing_movie_development
    ports:
      - "5433:5432"
  be:
    build: ./backend
    entrypoint: /usr/bin/entrypoint.sh
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      NODE_ENV: development
  fe:
    command: bash -c "yarn && yarn dev"
    build: ./frontend
    entrypoint: /usr/bin/entrypoint.sh
    volumes:
      - ./frontend:/myapp
    ports:
      - "3003:3003"
      - "9229:9229"
    environment:
      NODE_ENV: development
    depends_on:
      - be
